---
  - block:
    - name: "Make OVS (Debian/Ubuntu)"
      command: fakeroot ./debian/rules binary
      args:
        chdir: "{{ deb_dir }}"
      environment:
        DEB_BUILD_OPTIONS: 'parallel=8 nocheck'
      become: true

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
