---
  - block:
    - name: "Unpack OVS (Debian/Ubuntu)"
      unarchive:
        src: "/tmp/{{ ovs_package }}"
        dest: "{{ deb_base_dir }}"
      become: true

    - name: "Install OVS dependencies (Debian/Ubuntu)"
      apt:
        name: "{{ deb_deps }}"
        state: present
        update_cache: yes
      become: true

    when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
