---
  - block:
    - name: "Make OVS userplane (CentOS/RedHat)"
      command: rpmbuild -bb --without check -D "kversion `uname -r`" rhel/openvswitch.spec
      args:
        chdir: "{{ el_dir }}"
      environment:
        RPMBUILD_OPT: '--without check'
      become: true

    - name: "Make OVS kernel module (CentOS/RedHat)"
      command: rpmbuild -bb --without check -D "kversion `uname -r`" rhel/openvswitch-kmod-fedora.spec
      args:
        chdir: "{{ el_dir }}"
        creates: "/root/rpmbuild/RPMS/x86_64/openvswitch-kmod-{{ovs_version}}-1.el7.x86_64.rpm"
      environment:
        RPMBUILD_OPT: '--without check'
      become: true

    when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
