---
  - block:
    - name: Remove workspaces
      file:
        path: "{{ el_base_dir }}"
        state: absent
      become: true      

    - name: Create directory for CentOS/RedHat
      file:
        path: "{{ el_base_dir }}"
        state: directory
      become: true

    - name: Copy archive for CentOS/RedHat
      copy:
        remote_src: true
        src: "/tmp/{{ ovs_package }}"
        dest: "{{ el_base_dir }}"
      become: true

    - name: Unpack OVS for CentOS/RedHat
      unarchive: src=/tmp/{{ ovs_package }} dest={{ el_base_dir }}
      become: true

    - name: Copy patches and script to OVS directory
      copy:
        src: "{{ role_path }}/files/"
        dest: "{{ el_dir }}/"
        mode: 0755
      become: true

    - name: Apply OVS custom patches
      patch:      
        src: "{{ role_path }}/files/rollback-to-use-openflow-1.4-by-default.patch"
        basedir: "{{ el_dir }}"
        strip: 1
      become: true

    - name: Remove tar files
      file:
        path: "{{ el_base_dir }}/{{ ovs_package }}"
        state: absent

    - name: Compress source files into tar
      community.general.archive:
        path: "{{ el_dir }}"
        dest: "{{ el_base_dir }}/{{ ovs_package }}"
        format: gz
      become: true

    - name: Yum update
      yum:
        name: '*'
        state: latest
        update_cache: yes
        exclude: kernel*
      become: true

    - name: Add EPEL repos
      yum:
        name: "{{ epel_repos }}"
        state: installed
        update_cache: yes
      become: true

    - name: Install CentOS/RedHat OVS dependencies
      yum:
        name: "{{ el_deps }}"
        state: installed
        update_cache: yes
      become: true
    
    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive
      become: true

    when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
